### ISSUE TITLE
Capture entire page height

### ISSUE THREAD

**Issue by andrekutianski** [devopsgroup-io/siteshooter#48]
Its possible capture a screenshot with entire height of the page?

**Comment by stevebritton** [comment]
Hi @andrekutianski, siteshooter will capture an entire page's height. 

Are you having issues with page height? If so, please post your siteshooter.yml file and we'll take a peek at the issue you're experiencing.

-Steve

**Comment by andrekutianski** [comment]
Thanks @stevebritton it's works perfectly!
