### ISSUE TITLE
No such file on siteshooter default command...

### ISSUE THREAD

**Issue by reynaldoapb** [devopsgroup-io/siteshooter#61]
I've tried to run siteshooter default command on windows, so I expected to generate : 

--pdf
--screenshots
--sitemap

but I got an error.: 
  Error: Error: Error: ENOENT: no such file or directory, open 'C:\Sites\testesiteshooter\sitemap.xml'

Could you help me solve this issue?

**Comment by stevebritton** [comment]
Hey Reynald,

Please run the following command and let me know if that creates a sitemap.xml file for you:

`siteshooter --sitemap `

Also, which version of node are you running?

-Steve

**Comment by stevebritton** [comment]
No response in over a few months, so I'm closing this out.
