### ISSUE TITLE
Invalid Command Line Options Should Halt Operation

### ISSUE THREAD

**Issue by seth-reeser** [devopsgroup-io/siteshooter#95]
If an invalid option is passed to `siteshooter`, expected behavior would be to halt and provide an exception. Instead, it starts the default behavior of crawling.

![screen shot 2018-03-19 at 1 59 45 pm](https://user-images.githubusercontent.com/6510351/37613447-707cdf40-2b7e-11e8-8a93-1760c85c6f77.png)

**Comment by benhalverson** [comment]
i've also noticed this behavior and usually have my hands on ctrl c to stop it 👍
